---
- name: Load distro-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"
    - main.yml

- name: Include package tasks
  ansible.builtin.include_tasks: packages.yml

- name: Include per-user tasks
  ansible.builtin.include_tasks: per_user.yml
  loop: "{{ base_users }}"
  loop_control:
    loop_var: __base_user
    label: "{{ __base_user.name }}"

- name: Include timezone and locale tasks
  ansible.builtin.include_tasks: timezone_locale.yml

- name: Include SSH configuration tasks
  ansible.builtin.include_tasks: ssh.yml
