---
- name: Create bash config directories
  ansible.builtin.file:
    path: "{{ __base_user_home }}/.config/bash/conf.d"
    state: directory
    recurse: true
    owner: "{{ base_user }}"
    mode: "0755"
  become: true

- name: Deploy bashrc
  ansible.builtin.template:
    src: bashrc.j2
    dest: "{{ __base_user_home }}/.config/bash/bashrc"
    owner: "{{ base_user }}"
    mode: "0644"
  become: true

- name: Deploy profile
  ansible.builtin.template:
    src: profile.j2
    dest: "{{ __base_user_home }}/.config/bash/profile"
    owner: "{{ base_user }}"
    mode: "0644"
  become: true

- name: Create readline config directory
  ansible.builtin.file:
    path: "{{ __base_user_home }}/.config/readline"
    state: directory
    owner: "{{ base_user }}"
    mode: "0755"
  become: true

- name: Deploy inputrc
  ansible.builtin.template:
    src: inputrc.j2
    dest: "{{ __base_user_home }}/.config/readline/inputrc"
    owner: "{{ base_user }}"
    mode: "0644"
  become: true

- name: Symlink bashrc to home directory
  ansible.builtin.file:
    src: ".config/bash/bashrc"
    dest: "{{ __base_user_home }}/.bashrc"
    state: link
    force: true
    owner: "{{ base_user }}"
  become: true

- name: Symlink profile to home directory
  ansible.builtin.file:
    src: ".config/bash/profile"
    dest: "{{ __base_user_home }}/.profile"
    state: link
    force: true
    owner: "{{ base_user }}"
  become: true

- name: Symlink inputrc to home directory
  ansible.builtin.file:
    src: ".config/readline/inputrc"
    dest: "{{ __base_user_home }}/.inputrc"
    state: link
    force: true
    owner: "{{ base_user }}"
  become: true
