---
- name: Converge
  hosts: all
  become: true
  vars:
    base_users:
      - name: bwright
        authorized_keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITestKey1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA test-key-1"
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITestKey2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA test-key-2"
      - name: testuser
        authorized_keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITestKey3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA test-key-3"
  roles:
    - role: scbitworx.base
