---
- name: Prepare Arch Linux container
  hosts: archlinux
  gather_facts: false
  tasks:
    - name: Install Python, sudo, and openssh (Arch)
      ansible.builtin.raw: pacman -Syu --noconfirm python sudo openssh

    - name: Generate SSH host keys (Arch)
      ansible.builtin.raw: ssh-keygen -A

- name: Prepare Debian/Ubuntu containers
  hosts: debian:ubuntu
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - locales
          - openssh-server
        state: present

    - name: Create privilege separation directory
      ansible.builtin.file:
        path: /run/sshd
        state: directory
        mode: "0755"
